name: alamanaelrasyl
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7

  cached_network_image: ^3.3.1

  get_it: ^7.7.0
  go_router: ^8.0.0
  provider: ^6.1.2
  internet_connection_checker_plus: ^1.0.1
  shared_preferences: ^2.2.3

  url_launcher: ^6.3.0
#  new_version_plus: ^0.0.11
  device_info_plus: 9.1.2
  package_info_plus: 5.0.1
  share_plus: ^4.0.10
  path_provider: ^2.1.4

  sizer: ^2.0.15
  shimmer: ^3.0.0
  lottie: ^2.0.0

  youtube_player_flutter: ^9.0.1
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^4.0.4
  flutter_svg: ^1.1.6

  cloud_firestore: ^4.8.4 #
  firebase_core: ^2.15.0 #
  firebase_messaging: ^14.6.5 #
  flutter_local_notifications: ^17.2.1+2
  googleapis_auth: ^1.4.1 #

  equatable: ^2.0.5
  http: ^0.13.4
  html: ^0.15.4

#  payment
  flutter_braintree: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/image/logo.png"
    background_color:
    theme_color:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/

flutter_assets:
  assets_path: assets/
  output_path: lib/assets_manager/
  filename: assets.dart
flutter_intl:
  enabled: true
