// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRPb_zGkrk5MaBkXT1wOk5YVi0Yd50-o',
    appId: '1:80279920776:web:6ca0766a2c948377003f3d',
    messagingSenderId: '80279920776',
    projectId: 'alamanaerasyl',
    authDomain: 'alamanaerasyl.firebaseapp.com',
    storageBucket: 'alamanaerasyl.appspot.com',
    measurementId: 'G-HMFKF1NSBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDirqLBN05h3Pvkk7zQAfOs7x6VeUkNb2Q',
    appId: '1:80279920776:android:3594a638de53de43003f3d',
    messagingSenderId: '80279920776',
    projectId: 'alamanaerasyl',
    storageBucket: 'alamanaerasyl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs2LFYUCbuC4Mcw_UiDzro4s4glTUcRM8',
    appId: '1:80279920776:ios:5aa038a35a2c0921003f3d',
    messagingSenderId: '80279920776',
    projectId: 'alamanaerasyl',
    storageBucket: 'alamanaerasyl.appspot.com',
    iosClientId: '80279920776-16ek1q1o6809nkdp8c5v6br2kbcgbjf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanadAbuYousef',
  );
}
