// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFqRUnm-bBB0RSj0qIITl2HrhLgQz5sw',
    appId: '1:355042056705:web:ee97cf25d2afe1b469fe00',
    messagingSenderId: '355042056705',
    projectId: 'alamna-el-rasyl',
    authDomain: 'alamna-el-rasyl.firebaseapp.com',
    storageBucket: 'alamna-el-rasyl.appspot.com',
    measurementId: 'G-PLYB5KTC1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV9-oi_u_nNdgD4XFp99mHwaEebvAYeVU',
    appId: '1:355042056705:android:8756a6e6cee0514b69fe00',
    messagingSenderId: '355042056705',
    projectId: 'alamna-el-rasyl',
    storageBucket: 'alamna-el-rasyl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfeVjlU_jrIscCQZ8IucJsGrVs73KcLEc',
    appId: '1:355042056705:ios:3f5032c849b7098f69fe00',
    messagingSenderId: '355042056705',
    projectId: 'alamna-el-rasyl',
    storageBucket: 'alamna-el-rasyl.appspot.com',
    iosBundleId: 'com.mnemdev.alamnaelrasyl',
  );
}
